appiumUrl=${url}
enableAppiumOutput=${enableAppiumOutput}
androidApplicationPath=${appPath}
package=${package}
mainActivity=${mainActivity}
launchActivity=${launchActivity}
loginActivity=${loginActivity}
driverTimeoutSeconds=${driverTimeoutSeconds}
resultImage=${resultImage}
projectBuildPath=${project.build.directory}
defaultImagesPath=${project.build.directory}/../../tools/img/
androidToolsPath=${androidToolsPath}
defaultAudioPath=${project.build.directory}/../../tools/audio/
defaultVideoPath=${project.build.directory}/../../tools/video/
defaultEmail=${defaultEmail}
defaultEmailPassword=${defaultEmailPassword}
specialEmail=${specialEmail}
specialPassword=${specialPassword}
androidVersion=${androidVersion}
isTablet=true
testrailUser=smoketester+android@wire.com
testrailToken=vkEghsfuhYUqLIp66IZK-sH18RTPdYL.rtoQHtisa
showLogcat=${showLogcat}
packageAutoDetection=${packageAutoDetection}
isOnGrid=${isOnGrid}
browserName=${browserName}
enforceAppInstall=${enforceAppInstall}
