# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gradle"
    open-pull-requests-limit: 1
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "wireapp/android"

  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 1
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "wireapp/android"
