XS:
    name: size/XS
    lines: 10
    color: 3CBF00
S:
    name: size/S
    lines: 100
    color: 5D9801
M:
    name: size/M
    lines: 300
    color: 7F7203
L:
    name: size/L
    lines: 500
    color: A14C05
XL:
    name: size/XL
    lines: 1000
    color: C32607
    comment: |
        # Ups 🫰🟨
        This PR is too big. Please try to break it up into smaller PRs.
XXL:
    name: size/XXL
    lines: 100000
    color: E50009
    comment: |
        # Ups 🫰🟥
        This PR is too big. Please break it up into smaller PRs.
