# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger: none

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight tests
  branches:
    include:
    - main
    - develop

pr:
  autoCancel: true
  drafts: false
  branches:
    include:
    - develop
    - main

pool:
  vmImage: 'macos-latest'

steps:
- checkout: self
  submodules: true
- task: Gradle@2
  inputs:
    workingDirectory: ''
    jdkVersionOption: '1.11'
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    tasks: 'assembleDebug'
- task: CmdLine@2
  inputs:
    script: 'mv com.wire.android-* com.wire.android-public-debug.apk'
    workingDirectory: 'app/build/outputs/apk/public/debug/'
    failOnStderr: true
- task: AppCenterTest@1
  inputs:
    appFile: 'app/build/outputs/apk/public/debug/com.wire.android-public-debug.apk'
    artifactsDirectory: '$(Build.ArtifactStagingDirectory)/AppCenterTest'
    frameworkOption: 'espresso'
    credentialsOption: 'serviceEndpoint'
    serverEndpoint: 'Appcenter - Wire Android Reloaded'
    appSlug: 'Wire/Wire-Android-Reloaded'
    devices: 'sogmeang'
    localeOption: 'en_US'
    showDebugOutput: true
