# Coverage configuration
#
# Validate this file using the following command in root project:
# curl -X POST --data-binary @codecov.yml https://codecov.io/validate
# ----------------------
codecov:
    notify:
        wait_for_ci: false

coverage:
    status:
        project:
            default:
                # basic
                target: auto
                threshold: 2%
                base: auto
        patch: false

# Ignoring Paths
# --------------
# which folders/files to ignore
ignore:
    - ".*/test/.*"
    - "buildSrc/.*"
    - "kalium/.*"
    - ".*/androidTest/.*"
    - ".*/_version.py"
    - "setup.py"
    - ".*/_Screen.kt"
    - ".*/mock/.*"
    - ".*/theme/.*"
    - ".*/common/.*"
    - ".*/navigation/.*"

# Pull request comments:
# ----------------------
# Diff is the Coverage Diff of the pull request.
# Files are the files impacted by the pull request
comment:
    layout: diff, files, footer
    behavior: default
    require_changes: true
