"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_API_TOKEN"
"base_path": "."
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true

files: [
  {
    "source": "/app/src/main/res/values/strings.xml",
    "translation": "/app/src/main/res/values-%two_letters_code%/%original_file_name%",
    "languages_mapping": {
      "two_letters_code": {
        # map non-two letter codes here, left side is crowdin designation, right side is babel designation
        "me": "cnr-Latn",
        "sr-Cyrl-ME": "cnr-Cyrl",
        "sr": "sr-Cyrl",
        "sr-CS": "sr-Latn",
      },
  },
  {
    "source": "/features/cells/src/main/res/values/strings.xml",
    "translation": "/features/cells/src/main/res/values-%two_letters_code%/%original_file_name%",
    "languages_mapping": {
      "two_letters_code": {
        # map non-two letter codes here, left side is crowdin designation, right side is babel designation
        "me": "cnr-Latn",
        "sr-Cyrl-ME": "cnr-Cyrl",
        "sr": "sr-Cyrl",
        "sr-CS": "sr-Latn",
      },
  },
  {
    "source": "/features/sketch/src/main/res/values/strings.xml",
    "translation": "/features/sketch/src/main/res/values-%two_letters_code%/%original_file_name%",
    "languages_mapping": {
      "two_letters_code": {
        # map non-two letter codes here, left side is crowdin designation, right side is babel designation
        "me": "cnr-Latn",
        "sr-Cyrl-ME": "cnr-Cyrl",
        "sr": "sr-Cyrl",
        "sr-CS": "sr-Latn",
      },
  },
  {
    "source": "/core/ui-common/src/main/res/values/strings.xml",
    "translation": "/core/ui-common/src/main/res/values-%two_letters_code%/%original_file_name%",
    "languages_mapping": {
      "two_letters_code": {
        # map non-two letter codes here, left side is crowdin designation, right side is babel designation
        "me": "cnr-Latn",
        "sr-Cyrl-ME": "cnr-Cyrl",
        "sr": "sr-Cyrl",
        "sr-CS": "sr-Latn",
      },
  }
]
