"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_API_TOKEN"
"base_path": "."
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true

files: [
  {
    "source": "/app/src/main/res/values/strings.xml",
    "translation": "/app/src/main/res/values-%two_letters_code%/%original_file_name%",
  },
  {
    "source": "/features/sketch/src/main/res/values/strings.xml",
    "translation": "/features/sketch/src/main/res/values-%two_letters_code%/%original_file_name%",
  },
  {
    "source": "/core/ui-common/src/main/res/values/strings.xml",
    "translation": "/core/ui-common/src/main/res/values-%two_letters_code%/%original_file_name%",
  }
]
