"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_API_TOKEN"
"base_path": "."
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true

# Entries with the format '/**/src/main/res/values/string.xml' are added automatically
# via the addEntryToCrowdinFile tasks, but they are NOT removed automatically.
files: [
    {
        "source": "/app/src/main/res/values/strings.xml",
        "translation": "/app/src/main/res/values-%two_letters_code%/%original_file_name%"
    },
    {
        "source": "/core/ui-common/src/main/res/values/strings.xml",
        "translation": "/core/ui-common/src/main/res/values-%two_letters_code%/%original_file_name%"
    },
    {
        "source": "/features/cells/src/main/res/values/strings.xml",
        "translation": "/features/cells/src/main/res/values-%two_letters_code%/%original_file_name%"
    },
    {
        "source": "/features/meetings/src/main/res/values/strings.xml",
        "translation": "/features/meetings/src/main/res/values-%two_letters_code%/%original_file_name%"
    },
    {
        "source": "/features/sketch/src/main/res/values/strings.xml",
        "translation": "/features/sketch/src/main/res/values-%two_letters_code%/%original_file_name%"
    },
    {
        "source": "/features/sync/src/main/res/values/strings.xml",
        "translation": "/features/sync/src/main/res/values-%two_letters_code%/%original_file_name%"
    }
]
