kotlinx.datetime.Instant
com.wire.android.ui.home.conversations.folder.MoveConversationToFolderArgs
com.wire.kalium.logic.data.conversation.Conversation.ProtocolInfo
com.wire.kalium.logic.data.id.ConversationId
com.wire.kalium.logic.data.id.GroupID
com.wire.kalium.logic.data.id.PlainID
com.wire.kalium.logic.data.id.QualifiedID
