name: "Deploy to S3"
description: "Deploys build to AWS S3"
inputs:
  aws-access-key-id:
    required: true
    description: "The aws-access-key-id used to authenticate with AWS"
  aws-secret-access-key:
    required: true
    description: "The aws-secret-access-key used to authenticate with AWS"
  aws-bucket:
    required: true
    description: "The AWS bucket where to upload build"
  github-token:
    required: true
    description: "The GITHUB_TOKEN needed for adding comments into PRs"
  build-flavour:
    required: true
    description: "The build flavour (dev, staging, internal, beta, prod, fdroid)"
  build-variant:
    required: true
    description: "The build variant (benchmark, compat, compatrelease, debug, release)"
runs:
  using: "composite"
  steps:
    - name: Set APK full path
      id: path
      shell: bash
      run: |
        APK_FULL_PATH_REF="$(set -- app/build/outputs/apk/${{ inputs.build-flavour }}/${{ inputs.build-variant }}/com.wire.*.apk; echo $1)"
        echo "apk_full_path=$APK_FULL_PATH_REF" >> $GITHUB_OUTPUT
        unset APK_FULL_PATH_REF
    - name: Upload to S3 from PR
      if: github.event.pull_request.number != ''
      id: upload
      uses: hkusu/s3-upload-action@v2.1.0
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: 'eu-central-1'
        aws-bucket: ${{ inputs.aws-bucket }}
        destination-dir: "megazord/android/reloaded/${{ inputs.build-flavour }}/${{ inputs.build-variant }}/PR-${{ github.event.pull_request.number }}/"
        file-path: ${{ steps.path.outputs.apk_full_path }}
        output-file-url: 'true'
        public: true
    - name: Upload to S3 from branch
      if: github.event.pull_request.number == ''
      id: upload-from-branch
      uses: hkusu/s3-upload-action@v2.1.0
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: 'eu-central-1'
        aws-bucket: ${{ inputs.aws-bucket }}
        destination-dir: "megazord/android/reloaded/${{ inputs.build-flavour }}/${{ inputs.build-variant }}/"
        file-path: ${{ steps.path.outputs.apk_full_path }}
        output-file-url: 'true'
        public: true
    - name: Show URL
      if: github.event.pull_request.number != ''
      shell: bash
      env:
        EVENT_FILE_PATH: artifacts/Event File/event.json
        GITHUB_USER: ${{ github.actor }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        gh pr comment "${{ github.event.pull_request.number }}" --body "Built [wire-android-${{ inputs.build-flavour }}-${{ inputs.build-variant }}-pr-${{ github.event.pull_request.number }}.apk](${{ steps.upload.outputs.file-url }}) is available for download"
    - name: Generate version file
      if: github.event.pull_request.number != ''
      shell: bash
      run: ./gradlew generateVersionFile
    - name: Rename mapping file
      if: github.event.pull_request.number != ''
      shell: bash
      id: mapping
      run: |
        version_code=$(cat app/version.txt | grep 'VersionCode' | sed 's/VersionCode: //')
        version_name=$(cat app/version.txt | grep 'VersionName' | sed 's/VersionName: //')
        capitalized_variant=$(echo "${{ inputs.build-variant }}" | awk '{print toupper($0)}')
        echo "Capitalized Variant: $capitalized_variant"
        mapping_full_path="app/build/outputs/mapping/${{ inputs.build-flavour }}$capitalized_variant/mapping.txt"
        new_mapping_file_name="mapping-$version_name-$version_code.txt"
        mv "$mapping_full_path" "$new_mapping_file_name"
        # Set the new mapping file name as an environment variable
        echo "new_mapping_file_name=$new_mapping_file_name" >> $GITHUB_ENV
    - name: Upload mapping file to S3 from branch
      if: github.event.pull_request.number != ''
      id: upload-mapping-from-branch
      uses: hkusu/s3-upload-action@v2.1.0
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: 'eu-central-1'
        aws-bucket: ${{ inputs.aws-bucket }}
        destination-dir: "megazord/android/reloaded/${{ inputs.build-flavour }}/${{ inputs.build-variant }}/"
        file-path: ${{ env.new_mapping_file_name }}
        output-file-url: 'true'
        public: true
