name: "Release Candidate"

on:
  push:
    branches:
      - release/candidate
  merge_group:
    types: [ checks_requested ]
    branches: [ release/candidate ]
  pull_request:
    branches:
      - release/candidate
    types: [ opened, synchronize ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.merge_group.head_sha }}
  cancel-in-progress: true

jobs:
  # Build for PR and merge group validation
  build-validation:
    if: github.event_name == 'merge_group' || (github.event.pull_request.head.repo.full_name == github.repository && github.event_name == 'pull_request')
    uses: ./.github/workflows/build-unified.yml
    with:
      build-config: |
        [
          {
            "flavor": "Staging",
            "variant": "Compat",
            "keystore-type": "internal",
            "build-type": "apk",
            "generate-version-file": false,
            "deployment-targets": "[{\"type\": \"s3\"}]"
          }
        ]
      enable-deployment: true
    secrets: inherit

  # Build for direct pushes to release/candidate
  build-release-candidate:
    if: github.event_name == 'push' && github.ref_name == 'release/candidate'
    uses: ./.github/workflows/build-unified.yml
    with:
      build-config: |
        [
          {
            "flavor": "Staging",
            "variant": "Compat",
            "keystore-type": "internal",
            "build-type": "apk",
            "generate-version-file": false,
            "deployment-targets": "[{\"type\": \"s3\"}]"
          },
          {
            "flavor": "Internal",
            "variant": "Compat",
            "keystore-type": "internal",
            "build-type": "both",
            "generate-version-file": false,
            "deployment-targets": "[{\"type\": \"s3\"}, {\"type\": \"google-play\", \"package-name\": \"com.wire.internal\", \"track\": \"production\", \"status\": \"completed\"}]"
          }
        ]
      enable-deployment: true
    secrets: inherit
