name: 'Close stale issues and PR'

# **What it does**: Mark issues and pull requests after no updates for 30 days. After that only issues will be automatically closed after 7 days of inactivity.
# **Why we have it**: We want to manage our queue of issues and pull requests.
# **Who does it impact**: Everyone collaborating on the project.

on:
    schedule:
        -   cron: '10 0 * * *'

jobs:
    stale:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/stale@v8
                with:
                    days-before-stale: 30
                    days-before-close: 7

                    stale-pr-message: 'This PR is stale because it has been open 30 days with no activity. Please update it or close it in case is not relevant anymore.'
                    stale-pr-label: 'stale'
                    exempt-pr-labels: 'WIP'
                    exempt-draft-pr: true
                    days-before-pr-close: -1 # never close PRs

                    stale-issue-message: 'This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 7 days.'
                    stale-issue-label: 'stale'
                    exempt-issue-labels: 'pinned, security'
                    close-issue-message: 'This issue was closed because it has been stalled for 7 days with no activity.'
                    days-before-issue-close: 7
