name: "Testing Test Build App"

on:
    merge_group:
    pull_request:
        types: [ opened, synchronize ] # Don't rerun on `edited` to save time
    workflow_call:

jobs:
    testing-build-app:
        runs-on: buildjet-8vcpu-ubuntu-2204
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    submodules: recursive # Needed in order to fetch Kalium sources for building
                    fetch-depth: 0
            -   name: Set up JDK 17
                uses: buildjet/setup-java@v4
                with:
                    java-version: '17'
                    distribution: 'temurin'
                    cache: gradle
            -   name: Build Staging Compat
                env:
                    GITHUB_USER: ${{ github.actor }}
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: |
                    ./gradlew assembleStagingCompat -p ./ --no-daemon
    uplod-to-s3:
        name: "Upload APK staging compat"
        needs: [ testing-build-app ]
        uses: ./.github/workflows/upload-aws-s3.yml
        with:
            flavour: "staging"
            buildType: "compat"
