name: "Testing Test Build App"

on:
    merge_group:
    pull_request:
        types: [ opened, synchronize, edited ]
    workflow_call:

jobs:
    testing-build-app:
        runs-on: buildjet-8vcpu-ubuntu-2204
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    submodules: recursive # Needed in order to fetch Kalium sources for building
                    fetch-depth: 0
            -   name: Set up JDK 17
                uses: buildjet/setup-java@v4
                with:
                    java-version: '17'
                    distribution: 'temurin'
                    cache: gradle
            -   name: Build Staging Compat
                env:
                    GITHUB_USER: ${{ github.actor }}
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: |
                    ./gradlew assembleStagingCompat -p ./ --no-daemon
                    cp app/build/outputs/apk/staging/compat/com.wire.*.apk wire-android-staging-pr-${{ github.event.pull_request.number }}.apk

            -   name: Checking ...
                run: |
                    echo "AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}"

            -   name: Uploading to S3
                id: upload
                uses: hkusu/s3-upload-action@v2.1.0
                with:
                    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    aws-region: 'us-west-1'
                    aws-bucket: ${{ secrets.AWS_S3_BUCKET }}
                    destination-dir: "megazord/android/reloaded/staging/compat/"
                    file-path: './wire-android-staging-pr-${{ github.event.pull_request.number }}.apk'
                    output-file-url: 'true'

            -   name: Show URL
                env:
                    EVENT_FILE_PATH: artifacts/Event File/event.json
                    GITHUB_USER: ${{ github.actor }}
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: |
                    gh pr comment "${{ github.event.pull_request.number }}" --body "APKs built during build-by-boris are available [here](${{ steps.upload.outputs.file-url }})"
