name: "Upload builds"

on:
#    pull_request_target:
#        types: [ opened, edited, synchronize ]

#    workflow_dispatch:
#        inputs:
#            baseBranch:
#                description: "Base branch to create the PR and update the localization strings"
#                required: true
#                default: "develop"
#                type: choice
#                options:
#                    - "develop"
#                    - "release/candidate"
    workflow_call:
        inputs:
            flavour:
                required: true
                type: string
            buildType:
                required: true
                type: string

jobs:
    deploy-to-s3:
        needs: [ testing-build-app ]
        runs-on: ubuntu-latest
        steps:
            -   name: Uploading
                uses: hkusu/s3-upload-action@v2
                env:
                    GITHUB_USER: ${{ github.actor }}
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    aws-region: 'us-west-1'
                    aws-bucket: ${{ secrets.AWS_S3_BUCKET }}
                    destination-dir: "megazord/android/reloaded/${inputs.flavour}/${inputs.buildType}/"
                    file-path: './app/build/outputs/apk/${inputs.flavour}/${inputs.buildType}/com.wire.*.apk'
                    output-file-url: 'true'

            -   name: Show URL
                run: echo '${{ steps.upload.outputs.file-url }}'
