name: "Upload builds"

on: push

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            -   uses: jakejarvis/s3-sync-action@master
                with:
                    args: --acl public-read --follow-symlinks --delete
                env:
                    AWS_S3_BUCKET: "z-lohika"
                    DEST_DIR: "megazord/android/reloaded/${params.FLAVOR.toLowerCase()}/${params.BUILD_TYPE.toLowerCase()}/"
                    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    AWS_REGION: 'us-west-1'
                    SOURCE_DIR: "app/build/outputs/apk/${params.FLAVOR.toLowerCase()}/${params.BUILD_TYPE.toLowerCase()}/"
