name: "Upload builds"

on:
    workflow_call:
        inputs:
            flavour:
                required: true
                type: string
            buildType:
                required: true
                type: string

jobs:
    deploy-to-s3:
        runs-on: buildjet-8vcpu-ubuntu-2204
        env:
            GITHUB_USER: ${{ github.actor }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    submodules: recursive # Needed in order to fetch Kalium sources for building
                    fetch-depth: 0

            -   name: Print secret 1
                run: |
                    echo "Secrets: ${{ secrets.AWS_ACCESS_KEY_ID }} "
                    env

            -   name: Print secret 2
                run: |
                    echo "Secrets: ${{ secrets.AWS_SECRET_ACCESS_KEY }} "
                    env

            -   name: Print secret 3
                run: |
                    echo "Secrets: ${{ secrets.AWS_S3_BUCKET }} "
                    env

            -   name: Uploading
                uses: hkusu/s3-upload-action@v2.1.0
                with:
                    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    aws-region: 'us-west-1'
                    aws-bucket: ${{ secrets.AWS_S3_BUCKET }}
                    destination-dir: "megazord/android/reloaded/${inputs.flavour}/${inputs.buildType}/"
                    file-path: './app/build/outputs/apk/${inputs.flavour}/${inputs.buildType}/com.wire.*.apk'
                    output-file-url: 'true'

            -   name: Show URL
                run: echo '${{ steps.upload.outputs.file-url }}'
