name: "Upload builds"

on:
#    pull_request_target:
#        types: [ opened, edited, synchronize ]

#    workflow_dispatch:
#        inputs:
#            baseBranch:
#                description: "Base branch to create the PR and update the localization strings"
#                required: true
#                default: "develop"
#                type: choice
#                options:
#                    - "develop"
#                    - "release/candidate"
    workflow_call:
        inputs:
            flavour:
                required: true
                type: string
            buildType:
                required: true
                type: string

jobs:
    deploy:
        needs: [ build-app ]
        runs-on: ubuntu-latest
        steps:
            -   uses: jakejarvis/s3-sync-action@master
                with:
                    args: --acl public-read --follow-symlinks --delete
                env:
                    AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
                    DEST_DIR: "megazord/android/reloaded/${inputs.flavour}/${inputs.buildType}/"
                    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    AWS_REGION: 'us-west-1'
                    SOURCE_DIR: "app/build/outputs/apk/${inputs.flavour}/${inputs.buildType}/com.wire.*.apk"
