name: "Upload builds"

on:
    workflow_call:
        inputs:
            flavour:
                required: true
                type: string
            buildType:
                required: true
                type: string
        secrets:
            aws-access-key-id:
                required: true
            aws-secret-access-key:
                required: true
            aws-bucket:
                required: true

permissions:
    contents: read

jobs:
    deploy-to-s3:
        runs-on: buildjet-8vcpu-ubuntu-2204
        env:
            GITHUB_USER: ${{ github.actor }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
#            -   name: Checkout
#                uses: actions/checkout@v4
#                with:
#                    submodules: recursive # Needed in order to fetch Kalium sources for building
#                    fetch-depth: 0

            -   name: Checking 4
                run: |
                    ls -la ./

            -   name: Checking 3
                run: |
                    ls -la ./app

            -   name: Checking 2
                run: |
                    ls -la ./app/build/outputs/apk

            -   name: Checking 1
                run: |
                    ls -la ./app/build/outputs/apk/${{inputs.flavour}}

            -   name: Checking 0
                run: |
                    ls -la ./app/build/outputs/apk/${{inputs.flavour}}/${{inputs.buildType}}/

            -   name: Uploading
                uses: hkusu/s3-upload-action@v2.1.0
                with:
                    aws-access-key-id: ${{ secrets.aws-access-key-id }}
                    aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
                    aws-region: 'us-west-1'
                    aws-bucket: ${{ secrets.aws-bucket }}
                    destination-dir: "megazord/android/reloaded/${{inputs.flavour}}/${{inputs.buildType}}/"
                    file-path: './app/build/outputs/apk/${{inputs.flavour}}/${{inputs.buildType}}/com.wire.*.apk'
                    output-file-url: 'true'

            -   name: Show URL
                run: echo '${{ steps.upload.outputs.file-url }}'
